### ISSUE TITLE
Error when running tests

### ISSUE THREAD

**Issue by demoneaux** [jlongster/prettier#10]
I'm running Node 6.2.1 on Windows 10. When running `npm test` on a fresh repo, I get the following error:

```
$ npm test

> prettier@0.0.2 test C:\Users\weeseng\Documents\GitHub\prettier
> jest

TypeError: string.replace is not a function
    at string (C:\Users\weeseng\Documents\GitHub\prettier\node_modules\jest-util\build\index.js:45:19)
    at p (C:\Users\weeseng\Documents\GitHub\prettier\node_modules\jest\node_modules\jest-cli\build\SearchSource.js:65:26)
    at new SearchSource (C:\Users\weeseng\Documents\GitHub\prettier\node_modules\jest\node_modules\jest-cli\build\SearchSource.js:101:34)
    at Runtime.createHasteContext.then.hasteMap (C:\Users\weeseng\Documents\GitHub\prettier\node_modules\jest\node_modules\jest-cli\build\jest.js:191:20)
    at process._tickCallback (internal/process/next_tick.js:103:7)
npm ERR! Test failed.  See above for more details.
```

Not too familiar with Jest, so I can't really help debug :(

**Comment by jlongster** [comment]
Hm, thanks for the report! I will look into it later today. I just cloned a fresh repo and it worked locally.

**Comment by demoneaux** [comment]
I've tried it out, and have a fix locally. Will send a PR soon!
