### ISSUE TITLE
Cannot run on node 4

### ISSUE THREAD

**Issue by guicar** [jlongster/prettier#25]
My `node --version`:
```
v4.4.7
```
My `npm --version`:
```
3.10.5
```

When I run:
```
npm i prettier
./node_modules/.bin/prettier
```
I get the following error:
```
node_modules/prettier/bin/prettier:33
let input;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

I wonder if I missed something or if the package should be compiled with Babel to es5.

**Comment by jlongster** [comment]
This should be fixed inhttps://github.com/jlongster/prettier/commit/4abb8ce5449b68dec1d61d9787802f606a757bc1. Just published 0.0.3 so you can try that.
