### ISSUE TITLE
Template string as function argument causes exception

### ISSUE THREAD

**Issue by arnarthor** [jlongster/prettier#254]
```js
const runProc = exec(`node ./build-support/tasks/taskRunner.js -c ${args.task} -s ${service}`, (error, stdout, stderr) => {
```

This code causes this error

```
{ AssertionError: ',' === '`'
    at fixTemplateLiteral (/Users/arnarthorsveinsson/.config/yarn/global/node_modules/prettier/src/util.js:156:10)
    at Object.util.fixFaultyLocations (/Users/arnarthorsveinsson/.config/yarn/global/node_modules/prettier/src/util.js:97:5)
    at getSortedChildNodes (/Users/arnarthorsveinsson/.config/yarn/global/node_modules/prettier/src/comments.js:25:8)
    at getSortedChildNodes (/Users/arnarthorsveinsson/.config/yarn/global/node_modules/prettier/src/comments.js:61:5)
    at getSortedChildNodes (/Users/arnarthorsveinsson/.config/yarn/global/node_modules/prettier/src/comments.js:61:5)
    at decorateComment (/Users/arnarthorsveinsson/.config/yarn/global/node_modules/prettier/src/comments.js:71:20)
    at decorateComment (/Users/arnarthorsveinsson/.config/yarn/global/node_modules/prettier/src/comments.js:85:7)
    at decorateComment (/Users/arnarthorsveinsson/.config/yarn/global/node_modules/prettier/src/comments.js:85:7)
    at decorateComment (/Users/arnarthorsveinsson/.config/yarn/global/node_modules/prettier/src/comments.js:85:7)
    at decorateComment (/Users/arnarthorsveinsson/.config/yarn/global/node_modules/prettier/src/comments.js:85:7)
  name: 'AssertionError',
  actual: ',',
  expected: '`',
  operator: '===',
  message: '\',\' === \'`\'',
  generatedMessage: true }
```

Changing the code to 
```js
const command = `node ./build-support/tasks/taskRunner.js -c ${args.task} -s ${service}`;
const runProc = exec(command, err => {
```

Fixes the error

**Comment by vjeux** [comment]
This has been fixed in #218, need a new release to be able to use it :)
