### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by Agusum** [jlongster/prettier#269]
[Enter steps to reproduce below:]

1. Just tried running ctrl+alt+f and got the following error. Tried it with the same JS code in Visual Studio Code and it runs fine.

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [prettier-atom](https://github.com/jlongster/prettier-atom) package, v0.0.7

### Stack Trace

Uncaught TypeError: Cannot read property 'endsWith' of undefined

```
At /Users/agusv/.atom/packages/prettier-atom/lib/helpers.js:15

TypeError: Cannot read property 'endsWith' of undefined
  at SUPPORTED_FILE_TYPES.some.ext (/Users/agusv/.atom/packages/prettier-atom/lib/helpers.js:15:74)
  at Array.some (native)
  at isFileTypeSupported (/Users/agusv/.atom/packages/prettier-atom/lib/helpers.js:15:58)
  at Object.format (/Users/agusv/.atom/packages/prettier-atom/lib/helpers.js:43:30)
  at atom-workspace.format (/Users/agusv/.atom/packages/prettier-atom/lib/prettier.js:15:39)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)

```

### Commands

```
 10x -0:57.1.0 pane:reopen-closed-item (input.hidden-input)
     -0:44 core:backspace (input.hidden-input)
     -0:00.1.0 prettier:format (input.hidden-input)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "node-debugger",
      "tree-view"
    ],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.4.8 (inactive)
atom-material-ui, v1.3.9 (inactive)
base16-eighties-dark, v2.1.1 (inactive)
dracula-theme, v2.0.0 (inactive)
format-javascript-comment, v0.2.2 (active)
monokai, v0.18.0 (inactive)
node-debugger, v1.10.0 (inactive)
nuclide, v0.197.0 (active)
prettier-atom, v0.0.7 (active)
script, v3.14.0 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.4.0 (inactive)
solarized-seti-ui, v0.8.6 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by vramana** [comment]
Please file the bug on prettier-atom repo. Closing this since this bug is not related to prettier itself. 

I really wish github had issue moving feature.

**Comment by hzoo** [comment]
😊 @vramana we just setup something to do that in babel (hopefully can generalize it soonish)

**Comment by jlongster** [comment]
Moved to https://github.com/jlongster/prettier-atom/issues/27
