### ISSUE TITLE
Runtime assertion error in fixTemplateLiteral

### ISSUE THREAD

**Issue by sophistifunk** [jlongster/prettier#270]
* Prettier `0.0.7`
* Source gist: https://gist.github.com/sophistifunk/9b2c3bf67d1324dc76ca9b501aea7f43
* Run with `prettier --write --print-width 160 --tab-width 4 src/js/components/PipelineGraph.jsx`
* Gives me the following:

```
src/js/components/PipelineGraph.jsx
{ AssertionError: ' ' === '`'
    at fixTemplateLiteral (/Users/josh/tmp/fresh-bo-checkout/jenkins-design-language/node_modules/prettier/src/util.js:156:10)
    at Object.util.fixFaultyLocations (/Users/josh/tmp/fresh-bo-checkout/jenkins-design-language/node_modules/prettier/src/util.js:97:5)
    at getSortedChildNodes (/Users/josh/tmp/fresh-bo-checkout/jenkins-design-language/node_modules/prettier/src/comments.js:25:8)
    at getSortedChildNodes (/Users/josh/tmp/fresh-bo-checkout/jenkins-design-language/node_modules/prettier/src/comments.js:61:5)
    at decorateComment (/Users/josh/tmp/fresh-bo-checkout/jenkins-design-language/node_modules/prettier/src/comments.js:71:20)
    at decorateComment (/Users/josh/tmp/fresh-bo-checkout/jenkins-design-language/node_modules/prettier/src/comments.js:85:7)
    at decorateComment (/Users/josh/tmp/fresh-bo-checkout/jenkins-design-language/node_modules/prettier/src/comments.js:85:7)
    at decorateComment (/Users/josh/tmp/fresh-bo-checkout/jenkins-design-language/node_modules/prettier/src/comments.js:85:7)
    at decorateComment (/Users/josh/tmp/fresh-bo-checkout/jenkins-design-language/node_modules/prettier/src/comments.js:85:7)
    at decorateComment (/Users/josh/tmp/fresh-bo-checkout/jenkins-design-language/node_modules/prettier/src/comments.js:85:7)
  name: 'AssertionError',
  actual: ' ',
  expected: '`',
  operator: '===',
  message: '\' \' === \'`\'',
  generatedMessage: true }
```

**Comment by demoneaux** [comment]
This has been fixed in #218 and will be released in the next version bump.

**Comment by sophistifunk** [comment]
Sweet!

**Comment by jlongster** [comment]
I'll release a new version in a few minutes.

**Comment by jlongster** [comment]
0.0.8 should be out
