### ISSUE TITLE
Exception in printFunctionParams with Flow FunctionTypeAnnotation with rest params

### ISSUE THREAD

**Issue by lrowe** [jlongster/prettier#349]
Running prettier version 0.0.9 on this input file errors:
```js
// @flow
type FuncWithOnlyRest = (...rest) => any;
```

Stack trace:
```
$ node_modules/.bin/prettier prettierfail.js 
TypeError: Cannot read property 'type' of null
    at printFunctionParams (/Users/lrowe/drive/devel/rewrite/node_modules/prettier/src/printer.js:1769:41)
    at genericPrintNoParens (/Users/lrowe/drive/devel/rewrite/node_modules/prettier/src/printer.js:1311:33)
    at genericPrint (/Users/lrowe/drive/devel/rewrite/node_modules/prettier/src/printer.js:70:28)
    at p (/Users/lrowe/drive/devel/rewrite/node_modules/prettier/src/printer.js:41:12)
    at exports.printComments (/Users/lrowe/drive/devel/rewrite/node_modules/prettier/src/comments.js:273:17)
    at printGenerically (/Users/lrowe/drive/devel/rewrite/node_modules/prettier/src/printer.js:39:12)
    at FastPath.call (/Users/lrowe/drive/devel/rewrite/node_modules/prettier/src/fast-path.js:114:16)
    at genericPrintNoParens (/Users/lrowe/drive/devel/rewrite/node_modules/prettier/src/printer.js:1471:14)
    at genericPrint (/Users/lrowe/drive/devel/rewrite/node_modules/prettier/src/printer.js:70:28)
    at p (/Users/lrowe/drive/devel/rewrite/node_modules/prettier/src/printer.js:41:12)
```

Failing snippet in printer.js:
```js
  const lastParam = util.getLast(path.getValue().params);
  const canHaveTrailingComma = lastParam.type !== "RestElement" && !fun.rest;
```

Looks like FunctionTypeAnnotation is not quite the same structure as other functions:
```js
> path.getValue()
{ type: 'FunctionTypeAnnotation',
  start: 33,
  end: 49,
  loc: { start: { line: 2, column: 24 }, end: { line: 2, column: 40 } },
  params: [],
  rest: 
   { type: 'FunctionTypeParam',
     start: 37,
     end: 41,
     loc: { start: [Object], end: [Object] },
     name: null,
     optional: false,
     typeAnnotation: 
      { type: 'GenericTypeAnnotation',
        start: 37,
        end: 41,
        loc: [Object],
        typeParameters: null,
        id: [Object] } },
  returnType: 
   { type: 'AnyTypeAnnotation',
     start: 46,
     end: 49,
     loc: { start: [Object], end: [Object] } },
  typeParameters: null }
```

Working fine with ArrowFunctionExpression:
```js
var x = (...rest) => null;
```
```js
> path.getValue()
{ type: 'ArrowFunctionExpression',
  start: 8,
  end: 25,
  loc: { start: { line: 1, column: 8 }, end: { line: 1, column: 25 } },
  id: null,
  generator: false,
  expression: true,
  async: false,
  params: 
   [ { type: 'RestElement',
       start: 9,
       end: 16,
       loc: [Object],
       argument: [Object] } ],
  body: 
   { type: 'NullLiteral',
     start: 21,
     end: 25,
     loc: { start: [Object], end: [Object] } } }
```

**Comment by vjeux** [comment]
Sorry about this! I found and fixed this bug literally 5 minutes after doing the last release. I'm going to ship 0.0.10 this morning which fixes is. cc @jlongster

**Comment by vjeux** [comment]
#315
