### ISSUE TITLE
error: unknown type: "Import", when formatting webpack's dynamic import function

### ISSUE THREAD

**Issue by ryancole** [jlongster/prettier#457]
prettier version 0.11.0
prettier-atom version 0.11.0

I'm using webpack 2's `import` function ([link](https://webpack.js.org/guides/migrating/#code-splitting-with-es2015)). There's a [babel plugin](https://babeljs.io/docs/plugins/syntax-dynamic-import/) that enables babel to parse this syntax, called `syntax-dynamic-import`,

I see that it looks like prettier was updated to use this babel plugin as part of #51. I'm seeing the below error, though, which looks related to babel not parsing this function call correctly?

```
Error: unknown type: "Import"
    at genericPrintNoParens (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:1547:13)
    at genericPrint (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:41:28)
    at comments.printComments.p (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2430:12)
    at Object.printComments (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\comments.js:293:17)
    at printGenerically (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2428:21)
    at FastPath.call (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\fast-path.js:99:16)
    at genericPrintNoParens (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:515:14)
    at genericPrint (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:41:28)
    at comments.printComments.p (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2430:12)
    at Object.printComments (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\comments.js:293:17)
    at printGenerically (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2428:21)
    at FastPath.call (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\fast-path.js:99:16)
    at genericPrintNoParens (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:269:25)
    at genericPrint (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:41:28)
    at comments.printComments.p (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2430:12)
    at Object.printComments (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\comments.js:293:17)
    at printGenerically (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2428:21)
    at FastPath.call (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\fast-path.js:99:16)
    at genericPrintNoParens (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:593:31)
    at genericPrint (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:41:28)
    at comments.printComments.p (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2430:12)
    at Object.printComments (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\comments.js:293:17)
    at printGenerically (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2428:21)
    at C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:544:30
    at FastPath.each (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\fast-path.js:125:7)
    at C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:542:14
    at Array.forEach (native)
    at genericPrintNoParens (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:541:14)
    at genericPrint (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:41:28)
    at comments.printComments.p (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2430:12)
    at Object.printComments (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\comments.js:293:17)
    at printGenerically (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2428:21)
    at FastPath.map (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\fast-path.js:153:19)
    at genericPrintNoParens (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:639:52)
    at genericPrint (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:41:28)
    at comments.printComments.p (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2430:12)
    at Object.printComments (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\comments.js:293:17)
    at printGenerically (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2428:21)
    at FastPath.map (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\fast-path.js:153:19)
    at printArgumentsList (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:1661:22)
    at genericPrintNoParens (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:516:9)
    at genericPrint (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:41:28)
    at comments.printComments.p (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2430:12)
    at Object.printComments (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\comments.js:293:17)
    at printGenerically (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2428:21)
    at FastPath.call (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\fast-path.js:99:16)
    at printExportDeclaration (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:1841:21)
    at genericPrintNoParens (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:376:14)
    at genericPrint (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:41:28)
    at comments.printComments.p (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2430:12)
    at Object.printComments (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\comments.js:293:17)
    at printGenerically (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2428:21)
    at C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:1570:25
    at FastPath.map (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\fast-path.js:153:19)
    at printStatementSequence (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:1555:8)
    at C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:126:20
    at FastPath.call (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\fast-path.js:99:16)
    at genericPrintNoParens (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:124:14)
    at genericPrint (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:41:28)
    at comments.printComments.p (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2430:12)
    at Object.printComments (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\comments.js:293:17)
    at printGenerically (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2428:21)
    at FastPath.call (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\fast-path.js:99:16)
    at genericPrintNoParens (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:111:19)
    at genericPrint (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:41:28)
    at comments.printComments.p (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2430:12)
    at Object.printComments (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\comments.js:293:17)
    at printGenerically (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2428:21)
    at printAstToDoc (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\src\printer.js:2435:10)
    at format (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\index.js:44:15)
    at formatWithShebang (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\index.js:51:12)
    at Object.format (C:\Users\Ryan\.atom\packages\prettier-atom\node_modules\prettier\index.js:65:12)
    at executePrettier (C:\Users\Ryan\.atom\packages\prettier-atom\lib\helpers.js:24:21)
    at format (C:\Users\Ryan\.atom\packages\prettier-atom\lib\helpers.js:47:23)
    at Object.formatOnSaveIfEnabled (C:\Users\Ryan\.atom\packages\prettier-atom\lib\helpers.js:73:3)
    at C:\Users\Ryan\.atom\packages\prettier-atom\lib\prettier.js:16:60
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1122:20)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1114:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\src\text-editor.js:904:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\src\pane.js:738:18)
    at Pane.saveItem (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\src\pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\src\pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\src\workspace.js:693:35)
    at atom-workspace.core:save (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\src\register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\src\command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\src\window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (C:\Users\Ryan\AppData\Local\atom\app-1.13.0\resources\app.asar\src\window-event-handler.js:3:59)
```

Long paste, I know, but I didn't want to omit anything import.

Lastly, here's the code that triggers this error. Prettier is being used by prettier-atom in my case, and I've enabled format on save.

```js
import { routes } from "@ryancole/router";

export default routes([
  {
    path: "*",
    isNotFound: true,
    loadComponent: () => import("./client/page/Error")
  }
]);
```

**Comment by hzoo** [comment]
Oh this is just because the printer was never added for this (parser is valid). Should be an easy fix. (that's why it's erroring at src\printer.js)

**Comment by vjeux** [comment]
Thanks @hzoo for fixing it so quickly!
