### ISSUE TITLE
TypeError: fromString(...).join is not a function

### ISSUE THREAD

**Issue by JonnyWalker81** [jlongster/prettier#52]
I get the following errors when using JSX like the following:

`<InputGroup.Button><Button className="btn btn btn-primary" type="submit">Save</Button></InputGroup.Button>`

I think its because of the "." in InputGroup.Button.  If I take out that line then the file is able to be formatted.

prettier errors:
/usr/local/lib/node_modules/prettier/src/printer.js:1046
    ).join([ path.call(print, "object"), path.call(print, "property") ]);
      ^

TypeError: fromString(...).join is not a function
    at genericPrintNoParens (/usr/local/lib/node_modules/prettier/src/printer.js:1046:7)
    at genericPrint (/usr/local/lib/node_modules/prettier/src/printer.js:128:28)
    at p (/usr/local/lib/node_modules/prettier/src/printer.js:77:37)
    at exports.printComments (/usr/local/lib/node_modules/prettier/src/comments.js:276:17)
    at printGenerically (/usr/local/lib/node_modules/prettier/src/printer.js:77:12)
    at FastPath.call (/usr/local/lib/node_modules/prettier/src/fast-path.js:113:16)
    at genericPrintNoParens (/usr/local/lib/node_modules/prettier/src/printer.js:1106:14)
    at genericPrint (/usr/local/lib/node_modules/prettier/src/printer.js:128:28)
    at p (/usr/local/lib/node_modules/prettier/src/printer.js:77:37)
    at exports.printComments (/usr/local/lib/node_modules/prettier/src/comments.js:276:17)

**Comment by jlongster** [comment]
Whoops, you are totally right. Thanks. I'll fix this soon.
