### ISSUE TITLE
The trailing comma option add comma in function argument = exception

### ISSUE THREAD

**Issue by clempat** [jlongster/prettier#726]
# Step to reproduce (Long line exemple from CRA)
```
// index.js
var chalk = require('chalk');
console.log('To override this, specify the ' + chalk.green('homepage') + ' in your ' + chalk.cyan('package.json') + '.');
```

run `prettier --write --trailing-comma index.js`

# What do you see.

Result is:

```
console.log(
  "To override this, specify the " +
    chalk.green("homepage") +
    " in your " +
    chalk.cyan("package.json") +
    ".",
);
```

and running `node index.js`:

```
index.js:8
);
^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

# Expected behavior

Not adding the trailing comma. No exception

**Comment by clempat** [comment]
Sorry I try to get the issue out of the context and actually it worked as expected... Need to figure out  what the real problem is then.

**Comment by rhengles** [comment]
A solution for this is coming in #641

**Comment by clempat** [comment]
Great sorry did not see it when I searched for this.

**Comment by vjeux** [comment]
@jlongster your PR is long overdue, this is tripping people over very frequently.
